### ISSUE TITLE
NuGet Package Manager throws  FormatException on none english formats: Beta 3, 2015

### ISSUE THREAD

**Issue by DerAlbertCom** [NuGet/NuGet.VisualStudioExtension#7]
On a system with the Number format "German (Germany)" in the Region settings it is not possible to Update Nuget Packages.

Repro:

* Change Region Number format to "German (Germany)" (probably others)
*  Manage nuget packages in Visual Studio, switch filter to "Installed"

<pre>
Error occured:\nSystem.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at NuGet.Client.V3.VisualStudio.V3UIMetadataResource.ParseMetadata(JObject metadata)
   at NuGet.Client.V3.VisualStudio.V3UIMetadataResource.<GetMetadata>b__f(JObject item)
   at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.UI.PackageLoader.<LoadItems>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.InfiniteScrollList.<<LoadWork>b__7>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.InfiniteScrollList.<LoadWork>d__c.MoveNext()
</pre>

**Comment by csharpfritz** [comment]
We have issued an update to the extension that fixes this issue:

http://blog.nuget.org/20150226/nuget-3.0-beta2.html



Jeff

**Comment by DerAlbertCom** [comment]
ok, thanks.

**Comment by flts** [comment]
I was wondering if this fix is also going to be released for VS2013?
