### ISSUE TITLE
Just updated nuget 3 and nothing is working

### ISSUE THREAD

**Issue by Bartmax** [NuGet/NuGet.VisualStudioExtension#8]
I launched VS 2015 today to get some work done, and it says there's a nuget update so I updated it.
after that, I created a new project to test something out and no nuget was installed. opened previous projects and tryied to install update whatever from nuget and all fails. 

Mostly errors are project unavailable but I get failed to load dependencies and some other nuances while trying different stuff.

it fails everywhere and is unusable. How can I go back to prev version ? I don't even know which version was before and what gets installed now. 
```
System.Runtime.InteropServices.COMException (0x80004005): Project unavailable. ---> System.Runtime.InteropServices.COMException (0x80004005): Project unavailable.
   at EnvDTE.Project.get_Object()
   at NuGet.PackageManagement.VisualStudio.EnvDTEProjectUtility.GetReferences(Project project)
   at NuGet.PackageManagement.VisualStudio.EnvDTEProjectUtility.GetReferencedProjects(Project envDTEProject)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<>c__DisplayClass7.<GetDependentEnvDTEProjectsDictionary>b__6()
   at Microsoft.VisualStudio.Shell.InvokableAction.InvokeMethod()
   at Microsoft.VisualStudio.Shell.InvokableBase.Invoke()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__d2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

**Comment by danliu** [comment]
@Bartmax, VS 2015 seems to have some issues with extension update/uninstall. 

Can you follow the setup instructions on this blog post http://blog.nuget.org/20150226/nuget-3.0-beta2.html and see if your issue can be resolved?

**Comment by Bartmax** [comment]
@danliu effectively I'm identified as the early reporters on twitter :D I had all the issue described and yes, I fixed the problem removing the v3 endpoint. I also did wrote at SO : http://stackoverflow.com/questions/28782640/visual-studio-2015-nuget-error-on-non-mvc6-projects

thanks for the follow up, I completely forgot to update the issue here.
